name: Run Python Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          apt-get -y install make
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Run Linting with pylint
        run: make lint
      - name: Run Unit tests with pytest
        run: make unit
