name: Run Python Tests

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      # -
      #   name: Install Python 3
      #   uses: actions/setup-python@v1
      #   with:
      #     python-version: 3.10.11
      # -
      #   name: Install Dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install .[dev]
      # -
      #   name: Linting with pylint
      #   run: make lint
      # -
      #   name: Unit Testing and Coverage with pytest
      #   env:
      #     AWS_DEFAULT_REGION: us-east-1
      #   run: make unit
      # -
      #   name: Security Linting with bandit
      #   run: make security-lint
      # -
      #   name: Security Testing with safety
      #   run: make cve-check
      -
        name: String value replacement
        env:
          SERVICE_VERSION_VAR: "service.appVersion"
          IMAGE_TAG_VERSION_VAR: "service.image.tag"
          TARGET_FILE: ./tests/features/values.yml
        run: |
          make install-yq
          CURRENT_VERSION=$(yq -r '$(TARGET_VARIABLE)' $(TARGET_FILE))
          NEW_VERSION= $(echo "${CURRENT_VERSION}" | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./g')
          echo $NEW_VERSION
          make bump-version TARGET_VARIABLE=$SERVICE_VERSION_VAR INPUT_VALUE=$NEW_VERSION TARGET_FILE=$TARGET_FILE
          make bump-version TARGET_VARIABLE=$IMAGE_TAG_VERSION_VAR INPUT_VALUE=$NEW_VERSION TARGET_FILE=$TARGET_FILE
