name: Main

on:
  pull_request:
  push:
    branches:
      - main
    tags: ['v*.*.*']

jobs:
  tests:
    uses: ./.github/workflows/ci.yml
  
  docker-image-push:
    if: github.event_name == 'push'
    needs: [tests]
    uses: ./.github/workflows/docker.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  
  github-image-push:
    if: github.event_name == 'push'
    needs: [tests]
    uses: ./.github/workflows/github.yml
  
  github-release:
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs: [docker-image-push, github-image-push]
    uses: ./.github/workflows/release.yml
  
  deploy-to-pypi:
    if: startsWith(github.event.ref, 'refs/tags/v')
    needs: [docker-release]
    uses: ./.github/workflows/pypi.yml
