name: Main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags: ['v*.*.*']

jobs:
  tests:
    uses: ./.github/workflows/ci.yaml
  
  docker-image-push:
    needs: [tests]
    uses: ./.github/workflows/docker.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  
  github-image-push:
    needs: [tests]
    uses: ./.github/workflows/github.yml
  
  github-release:
    needs: [docker-image-push, github-image-push]
    uses: ./.github/workflows/release.yml
